name: Запрос функционала 💡
description: Создать отчет на введение нового функционала
labels: [ "идея", "сортировка" ]
assignees:
  - 13hz

body:
  - type: markdown
    attributes:
      value: Пожалуйста, заполните все поля ниже

  - type: textarea
    id: feature-description
    attributes:
      label: Описание функционала
      description: Опишите свою идею
      placeholder: Добавить новый фильтр скоров, что бы ....
    validations:
      required: true
